---
- hosts: mydata
  become: true
  remote_user: root
  tasks:  
  - name: create docker daemon file
    file:
      path: /etc/docker/daemon.json
      state: touch

  - name: add insecure registry to srv-data     
    shell:
      cmd: |
        cat > /etc/docker/daemon.json << EOF
        {
          "insecure-registries" : ["192.168.100.20:5000"]
        }
        EOF

  - name: Restart docker
    service:
      name: docker
      daemon_reload: yes
      state: restarted
      
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: Install Maven
    apt: name={{item}}
    with_items:
        - maven
 
  - name: install docker-compose
    shell:
      cmd: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

  - name: create directory if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0775
    with_items:
      - /home/vagrant/data
      - /home/vagrant/certs
      - /home/vagrant/passwd
      
  - name: creates registry
    shell:
      cmd: |
        sudo openssl req -x509 -newkey rsa:4096 -nodes -keyout /home/vagrant/certs/myregistry.key -out /home/vagrant/certs/myregistry.crt -days 365 -subj /CN=myregistry.my
        sudo docker run --entrypoint htpasswd registry:2 -Bbn keny azerty > /home/vagrant/passwd/htpasswd
        echo "
        ---
        version: '3.5'
        services:
          registry:
            restart: always
            image: registry:2
            container_name: registry
            ports:
              - 5000:5000
            environment:
              REGISTRY_HTTP_TLS_CERTIFICATE: /certs/myregistry.crt
              REGISTRY_HTTP_TLS_KEY: /certs/myregistry.key
              REGISTRY_AUTH: htpasswd
              REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
              REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            volumes:
              - ./data:/var/lib/registry
              - ./certs:/certs
              - ./passwd:/auth
            networks:
              - netregistry
          ui:
            restart: always
            image: 'joxit/docker-registry-ui:static'
            container_name: 'ui'
            ports:
              - '80:80'
            environment:
              REGISTRY_URL: 'https://192.168.100.20:5000'
              DELETE_IMAGES: 'true'
              REGISTRY_TITLE: 'MyRegistry'
            networks:
              - 'netregistry'
            depends_on:
              - 'registry'
        networks:
          netregistry:
            name: 'netregistry'
        " > /home/vagrant/docker-compose-registry.yml
        docker-compose -f /home/vagrant/docker-compose-registry.yml up -d
        sudo docker login https://192.168.100.20:5000 -u keny -p azerty
